"""Rebuild scene color SPIR-V variants after particle shading changes.
Usage: python phase4/compile_particle_shaders.py /path/to/dxc.exe
Also validates the four D3D12 variants. Other shader entries are untouched.
"""
import pathlib, re, struct, subprocess, sys, tempfile

def descriptors(words):
 names={}; dec={}; i=5
 while i<len(words):
  n=words[i]>>16; op=words[i]&65535; p=words[i+1:i+n]
  assert n>0
  if op==5: names[p[0]]=struct.pack("<"+"I"*len(p[1:]),*p[1:]).split(b"\0")[0].decode()
  if op==71 and p[1] in (33,34): dec.setdefault(p[0],{})[p[1]]=p[2]
  i+=n
 return {names[k]:(v[33],v[34]) for k,v in dec.items() if 33 in v and 34 in v}

root = pathlib.Path(__file__).resolve().parents[1]
header = root / "src/native/shaders/spirv/skate3_native_shaders_spirv.h"
text = header.read_text()
# Frozen RHI set/binding layout; see existing SPIR-V decorations.
bindings = {"b0":(0,0),"b1":(2,0),"b2":(3,0),"t0":(0,1),"t1":(0,2),
 "t2":(1,0),"t3":(0,3),"t4":(0,4),"t5":(1,4),"t6":(0,5),
 "t7":(1,5),"t8":(0,6),"t9":(1,6),"t10":(2,6),"s0":(4,0),"s1":(5,0)}
base = [sys.argv[1], str(root / "src/native/shaders/scene.hlsl"), "-E","ps_main",
        "-T","ps_6_0","-O3"]
with tempfile.TemporaryDirectory() as td:
 for defs, suffix in [((),""),(("HDR=1",),"_HDR_1"),(("SHOWCASE=1",),"_SHOWCASE_1"),
                     (("HDR=1","SHOWCASE=1"),"_HDR_1_SHOWCASE_1")]:
  flags = [arg for d in defs for arg in ("-D",d)]
  subprocess.run(base+flags+["-Fo",str(pathlib.Path(td)/"check.dxil")],check=True)
  out=pathlib.Path(td)/"check.spv"
  vk=["-spirv","-fspv-target-env=vulkan1.1"]
  for reg,(binding,descriptor_set) in bindings.items():
   vk += ["-fvk-bind-register",reg,"0",str(binding),str(descriptor_set)]
  subprocess.run(base+flags+vk+["-Fo",str(out)],check=True)
  data=out.read_bytes(); words=struct.unpack("<"+"I"*(len(data)//4),data)
  body="\n".join("    "+", ".join(f"0x{w:08x}" for w in words[i:i+8])+"," for i in range(0,len(words),8))
  name="k_scene_ps_main"+suffix
  pattern=r"static const uint32_t "+name+r"\[\] = \{.*?\};"
  previous=re.search(pattern,text,flags=re.S).group(0)
  oldwords=[int(w,16) for w in re.findall(r"0x[0-9a-fA-F]+",previous)]
  assert descriptors(oldwords)==descriptors(words), "RHI bindings changed: "+name
  # Keep the generated byte-count comment accurate too.
  text=re.sub(r"(// scene.hlsl : ps_main(?: \[[^\]]+\])? \()\d+( bytes\)\nstatic const uint32_t "+name+r"\[)",lambda m:m[1]+str(len(data))+m[2],text)
  text,count=re.subn(pattern,"static const uint32_t "+name+"[] = {\n"+body+"\n};",text,flags=re.S)
  assert count==1, name
  print(name,len(data),"bytes: D3D12 and Vulkan compiled")
header.write_text(text)
